version: "3.2"

services:
  ctf: # 
    container_name: hack
    privileged: true
    build:
      context: .
      dockerfile: ./Dockerfile.ctf
  cme: # 
    container_name: hack
    build:
      context: .
      dockerfile: ./Dockerfile.CrackMapExec     
  
